const specifications = [
    { label: "Customized Executive Desk", value: "L Shape/Straight" },
    { label: "Material", value: "Egger German Board" },
    { label: "Dimensions", value: "Can be Customized (Please contact our sale team)" },
    { label: "Finishes", value: "100+ Color Options" },
    { label: "Wire Managers", value: "Grommets for Every Desk" },
    { label: "Free Design Consultation", value: "by our expert design team" },
    { label: "Warranty", value: "5 Years" },
    { label: "Free Delivery and Installation", value: "within Dubai/Abu Dhabi/Sharjah/Ajman" },
    { label: "Delivery Lead-Time", value: "7-10 working days upon payment" },
];


export const seatingAllImagesLounge = [
    {
        id: 1,
        img: "/NavbarContentImg/Seating/Lounge/1.jpg",
        title: "AMAZE LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 2,
        img: "/NavbarContentImg/Seating/Lounge/2.jpg",
        title: "BEND LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 3,
        img: "/NavbarContentImg/Seating/Lounge/3.jpg",
        title: "FRED LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 4,
        img: "/NavbarContentImg/Seating/Lounge/4.jpg",
        title: "GOLDIE LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 5,
        img: "/NavbarContentImg/Seating/Lounge/5.jpg",
        title: "HUGO LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 6,
        img: "/NavbarContentImg/Seating/Lounge/6.jpg",
        title: "KING LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 7,
        img: "/NavbarContentImg/Seating/Lounge/7.jpg",
        title: "LEDGE LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 8,
        img: "/NavbarContentImg/Seating/Lounge/8.jpg",
        title: "NEON LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 9,
        img: "/NavbarContentImg/Seating/Lounge/9.jpg",
        title: "PUFF LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 10,
        img: "/NavbarContentImg/Seating/Lounge/10.jpeg",
        title: "RELAX LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 11,
        img: "/NavbarContentImg/Seating/Lounge/11.jpg",
        title: "SKY LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 12,
        img: "/NavbarContentImg/Seating/Lounge/12.jpg",
        title: "SWAN LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 13,
        img: "/NavbarContentImg/Seating/Lounge/13.jpg",
        title: "TIGO LOUNGE",
        sub_title: "Lounge",
        specifications,
    },
    {
        id: 14,
        img: "/NavbarContentImg/Seating/Lounge/14.jpg",
        title: "WING LOUNGE",
        sub_title: "Lounge",
        specifications,
    }
]

export const seatingAllImagesOfficeSofa = [
    {
        id: 1,
        img: "/NavbarContentImg/Seating/Office/1.jpeg",
        title: "AXEL SOFA",
        sub_title: "Office Sofa",
        specifications,
    },
    {
        id: 2,
        img: "/NavbarContentImg/Seating/Office/2.png",
        title: "CANDLE SOFA",
        sub_title: "Office Sofa",
        specifications,
    },
    {
        id: 3,
        img: "/NavbarContentImg/Seating/Office/3.png",
        title: "DELMA SOFA",
        sub_title: "Office Sofa",
        specifications,
    },
    {
        id: 4,
        img: "/NavbarContentImg/Seating/Office/4.png",
        title: "DEX SOFA",
        sub_title: "Office Sofa",
        specifications,
    },
    {
        id: 5,
        img: "/NavbarContentImg/Seating/Office/5.jpg",
        title: "DOME SOFA",
        sub_title: "Office Sofa",
        specifications,
    },
    {
        id: 6,
        img: "/NavbarContentImg/Seating/Office/6.png",
        title: "DONA SOFA",
        sub_title: "Office Sofa",
        specifications,
    },
    {
        id: 7,
        img: "/NavbarContentImg/Seating/Office/7.png",
        title: "JOULIE SOFA",
        sub_title: "Office Sofa",
        specifications,
    },
    {
        id: 8,
        img: "/NavbarContentImg/Seating/Office/8.jpg",
        title: "LAIZA SOFA",
        sub_title: "Office Sofa",
        specifications,
    },
    {
        id: 9,
        img: "/NavbarContentImg/Seating/Office/9.jpg",
        title: "LILA SOFA",
        sub_title: "Office Sofa",
        specifications,
    },
    {
        id: 10,
        img: "/NavbarContentImg/Seating/Office/10.png",
        title: "LAURA SOFA",
        sub_title: "Office Sofa",
        specifications,
    },
    {
        id: 11,
        img: "/NavbarContentImg/Seating/Office/11.jpg",
        title: "PETER SOFA",
        sub_title: "Office Sofa",
        specifications,
    },
    {
        id: 12,
        img: "/NavbarContentImg/Seating/Office/12.png",
        title: "VECTOR SOFA",
        sub_title: "Office Sofa",
        specifications,
    }
]