export const executiveDeskGallery = [
    { id: 1, img: "/Exec-Gallery/EG-1.jpeg" },
    { id: 2, img: "/Exec-Gallery/EG-2.jpeg" },
    { id: 3, img: "/Exec-Gallery/EG-3.jpeg" },
    { id: 4, img: "/Exec-Gallery/EG-4.jpeg" },
    { id: 5, img: "/Exec-Gallery/EG-5.jpeg" },
    { id: 6, img: "/Exec-Gallery/EG-6.jpeg" },
    { id: 7, img: "/Exec-Gallery/EG-7.jpeg" },
    { id: 8, img: "/Exec-Gallery/EG-8.jpg" },
    { id: 9, img: "/Exec-Gallery/EG-9.jpg" },
    { id: 10, img: "/Exec-Gallery/EG-10.jpg" },
    { id: 11, img: "/Exec-Gallery/EG-11.jpg" },
    { id: 12, img: "/Exec-Gallery/EG-12.jpg" },
    { id: 13, img: "/Exec-Gallery/EG-13.jpg" },
    { id: 14, img: "/Exec-Gallery/EG-14.jpg" },
    { id: 15, img: "/Exec-Gallery/EG-15.jpg" },
    { id: 16, img: "/Exec-Gallery/EG-16.jpeg" },
    { id: 17, img: "/Exec-Gallery/EG-17.jpeg" },
    { id: 18, img: "/Exec-Gallery/EG-18.jpeg" },
    { id: 19, img: "/Exec-Gallery/EG-19.jpeg" },
    { id: 20, img: "/Exec-Gallery/EG-20.jpeg" },
    { id: 21, img: "/Exec-Gallery/EG-21.jpeg" },
    { id: 21, img: "/Exec-Gallery/EG-22.jpeg" },
    { id: 23, img: "/Exec-Gallery/EG-23.jpeg" },
    { id: 24, img: "/Exec-Gallery/EG-24.jpeg" },
    { id: 25, img: "/Exec-Gallery/EG-25.jpeg" },
    { id: 26, img: "/Exec-Gallery/EG-26.jpeg" },
    { id: 27, img: "/Exec-Gallery/EG-27.jpeg" },
    { id: 28, img: "/Exec-Gallery/EG-28.jpeg" },
    { id: 29, img: "/Exec-Gallery/EG-29.jpeg" },
    { id: 30, img: "/Exec-Gallery/EG-30.jpeg" },
    { id: 31, img: "/Exec-Gallery/EG-20.jpeg" },
    { id: 32, img: "/Exec-Gallery/EG-10.jpg" },
    { id: 33, img: "/Exec-Gallery/EG-1.jpeg" },
    { id: 34, img: "/Exec-Gallery/EG-29.jpeg" },
    { id: 35, img: "/Exec-Gallery/EG-23.jpeg" },
    { id: 36, img: "/Exec-Gallery/EG-22.jpeg" },
    { id: 37, img: "/Exec-Gallery/EG-21.jpeg" },
    { id: 38, img: "/Exec-Gallery/EG-18.jpeg" },
    { id: 39, img: "/Exec-Gallery/EG-17.jpeg" },
    { id: 40, img: "/Exec-Gallery/EG-15.jpg" },
    { id: 41, img: "/Exec-Gallery/EG-13.jpg" },
    { id: 42, img: "/Exec-Gallery/EG-11.jpg" },
    { id: 43, img: "/Exec-Gallery/EG-2.jpeg" },
    { id: 44, img: "/Exec-Gallery/EG-8.jpg" },
    { id: 45, img: "/Exec-Gallery/EG-7.jpeg" },
    { id: 46, img: "/Exec-Gallery/EG-5.jpeg" },
    { id: 47, img: "/Exec-Gallery/EG-3.jpeg" },
    { id: 48, img: "/Exec-Gallery/EG-26.jpeg" },
    { id: 49, img: "/Exec-Gallery/EG-12.jpg" },
    { id: 50, img: "/Exec-Gallery/EG-25.jpeg" },
    { id: 51, img: "/Exec-Gallery/EG-21.jpeg" },
    { id: 52, img: "/Exec-Gallery/EG-15.jpg" },
    { id: 53, img: "/Exec-Gallery/EG-12.jpg" },
    { id: 54, img: "/Exec-Gallery/EG-11.jpg" },
    { id: 55, img: "/Exec-Gallery/EG-2.jpeg" },
    { id: 56, img: "/Exec-Gallery/EG-5.jpeg" },
]

export const workstationGallery = [
    { id: 1, img: "/Worksta-Gallery/WG-1.jpeg" },
    { id: 2, img: "/Worksta-Gallery/WG-2.jpeg" },
    { id: 3, img: "/Worksta-Gallery/WG-3.jpeg" },
    { id: 4, img: "/Worksta-Gallery/WG-4.jpg" },
    { id: 5, img: "/Worksta-Gallery/WG-5.jpg" },
    { id: 6, img: "/Worksta-Gallery/WG-6.jpg" },
    { id: 7, img: "/Worksta-Gallery/WG-7.jpg" },
    { id: 8, img: "/Worksta-Gallery/WG-8.jpg" },
    { id: 9, img: "/Worksta-Gallery/WG-9.jpg" },
    { id: 10, img: "/Worksta-Gallery/WG-10.jpg" },
    { id: 11, img: "/Worksta-Gallery/WG-11.jpeg" },
    { id: 12, img: "/Worksta-Gallery/WG-12.jpeg" },
    { id: 13, img: "/Worksta-Gallery/WG-13.jpeg" },
    { id: 14, img: "/Worksta-Gallery/WG-14.jpeg" },
    { id: 15, img: "/Worksta-Gallery/WG-15.jpeg" },
    { id: 16, img: "/Worksta-Gallery/WG-16.jpeg" },
    { id: 17, img: "/Worksta-Gallery/WG-17.jpeg" },
    { id: 18, img: "/Worksta-Gallery/WG-18.jpeg" },
    { id: 19, img: "/Worksta-Gallery/WG-19.jpeg" },
    { id: 20, img: "/Worksta-Gallery/WG-20.jpeg" },
    { id: 21, img: "/Worksta-Gallery/WG-21.jpeg" },
    { id: 21, img: "/Worksta-Gallery/WG-22.jpeg" },
    { id: 23, img: "/Worksta-Gallery/WG-23.jpeg" },
    { id: 24, img: "/Worksta-Gallery/WG-24.jpeg" },
    { id: 25, img: "/Worksta-Gallery/WG-25.jpeg" },
    { id: 26, img: "/Worksta-Gallery/WG-26.jpeg" },
    { id: 27, img: "/Worksta-Gallery/WG-27.jpeg" },
    { id: 28, img: "/Worksta-Gallery/WG-28.jpeg" },
    { id: 29, img: "/Worksta-Gallery/WG-29.jpeg" },
    { id: 30, img: "/Worksta-Gallery/WG-30.jpeg" },
    { id: 31, img: "/Worksta-Gallery/WG-1.jpeg" },
    { id: 32, img: "/Worksta-Gallery/WG-2.jpeg" },
    { id: 33, img: "/Worksta-Gallery/WG-3.jpeg" },
    { id: 34, img: "/Worksta-Gallery/WG-4.jpg" },
    { id: 35, img: "/Worksta-Gallery/WG-5.jpg" },
    { id: 36, img: "/Worksta-Gallery/WG-6.jpg" },
    { id: 37, img: "/Worksta-Gallery/WG-7.jpg" },
    { id: 38, img: "/Worksta-Gallery/WG-8.jpg" },
    { id: 39, img: "/Worksta-Gallery/WG-9.jpg" },
    { id: 40, img: "/Worksta-Gallery/WG-21.jpeg" },
    { id: 41, img: "/Worksta-Gallery/WG-23.jpeg" },
    { id: 42, img: "/Worksta-Gallery/WG-26.jpeg" },
    { id: 43, img: "/Worksta-Gallery/WG-27.jpeg" },
    { id: 44, img: "/Worksta-Gallery/WG-29.jpeg" },
    { id: 45, img: "/Worksta-Gallery/WG-24.jpeg" },
    { id: 46, img: "/Worksta-Gallery/WG-26.jpeg" },
    { id: 47, img: "/Worksta-Gallery/WG-23.jpeg" },
    { id: 48, img: "/Worksta-Gallery/WG-3.jpeg" },
    { id: 49, img: "/Worksta-Gallery/WG-8.jpg" },
    { id: 50, img: "/Worksta-Gallery/WG-12.jpeg" },
    { id: 51, img: "/Worksta-Gallery/WG-13.jpeg" },
    { id: 52, img: "/Worksta-Gallery/WG-16.jpeg" },
    { id: 53, img: "/Worksta-Gallery/WG-18.jpeg" },
    { id: 54, img: "/Worksta-Gallery/WG-19.jpeg" },
    { id: 55, img: "/Worksta-Gallery/WG-11.jpeg" },
    { id: 56, img: "/Worksta-Gallery/WG-14.jpeg" },
]

export const conferenceGallery = [
    { id: 1, img: "/Confere-Gallery/CG-1.jpeg" },
    { id: 2, img: "/Confere-Gallery/CG-2.jpeg" },
    { id: 3, img: "/Confere-Gallery/CG-3.jpg" },
    { id: 4, img: "/Confere-Gallery/CG-4.jpeg" },
    { id: 5, img: "/Confere-Gallery/CG-5.jpeg" },
    { id: 6, img: "/Confere-Gallery/CG-6.jpeg" },
    { id: 7, img: "/Confere-Gallery/CG-7.jpeg" },
    { id: 8, img: "/Confere-Gallery/CG-8.jpeg" },
    { id: 9, img: "/Confere-Gallery/CG-9.jpeg" },
    { id: 10, img: "/Confere-Gallery/CG-10.jpeg" },
    { id: 11, img: "/Confere-Gallery/CG-11.jpeg" },
    { id: 12, img: "/Confere-Gallery/CG-12.jpeg" },
    { id: 13, img: "/Confere-Gallery/CG-13.jpeg" },
    { id: 14, img: "/Confere-Gallery/CG-14.jpeg" },
    { id: 15, img: "/Confere-Gallery/CG-15.jpeg" },
    { id: 16, img: "/Confere-Gallery/CG-16.jpeg" },
    { id: 17, img: "/Confere-Gallery/CG-17.jpeg" },
    { id: 18, img: "/Confere-Gallery/CG-18.jpeg" },
    { id: 19, img: "/Confere-Gallery/CG-19.jpeg" },
    { id: 20, img: "/Confere-Gallery/CG-20.jpeg" },
    { id: 21, img: "/Confere-Gallery/CG-21.jpeg" },
    { id: 21, img: "/Confere-Gallery/CG-22.jpeg" },
    { id: 23, img: "/Confere-Gallery/CG-23.jpeg" },
    { id: 24, img: "/Confere-Gallery/CG-24.jpeg" },
    { id: 25, img: "/Confere-Gallery/CG-25.jpeg" },
    { id: 26, img: "/Confere-Gallery/CG-26.jpeg" },
    { id: 27, img: "/Confere-Gallery/CG-27.jpeg" },
    { id: 28, img: "/Confere-Gallery/CG-28.jpeg" },
    { id: 29, img: "/Confere-Gallery/CG-29.jpeg" },
    { id: 30, img: "/Confere-Gallery/CG-30.jpeg" },
    { id: 31, img: "/Confere-Gallery/CG-1.jpeg" },
    { id: 32, img: "/Confere-Gallery/CG-2.jpeg" },
    { id: 33, img: "/Confere-Gallery/CG-3.jpg" },
    { id: 34, img: "/Confere-Gallery/CG-4.jpeg" },
    { id: 35, img: "/Confere-Gallery/CG-5.jpeg" },
    { id: 36, img: "/Confere-Gallery/CG-6.jpeg" },
    { id: 37, img: "/Confere-Gallery/CG-7.jpeg" },
    { id: 38, img: "/Confere-Gallery/CG-8.jpeg" },
    { id: 39, img: "/Confere-Gallery/CG-9.jpeg" },
    { id: 40, img: "/Confere-Gallery/CG-12.jpeg" },
    { id: 41, img: "/Confere-Gallery/CG-13.jpeg" },
    { id: 42, img: "/Confere-Gallery/CG-14.jpeg" },
    { id: 43, img: "/Confere-Gallery/CG-17.jpeg" },
    { id: 44, img: "/Confere-Gallery/CG-8.jpeg" },
    { id: 45, img: "/Confere-Gallery/CG-19.jpeg" },
    { id: 46, img: "/Confere-Gallery/CG-19.jpeg" },
    { id: 47, img: "/Confere-Gallery/CG-11.jpeg" },
    { id: 48, img: "/Confere-Gallery/CG-21.jpeg" },
    { id: 49, img: "/Confere-Gallery/CG-23.jpeg" },
    { id: 50, img: "/Confere-Gallery/CG-26.jpeg" },
    { id: 51, img: "/Confere-Gallery/CG-28.jpeg" },
    { id: 52, img: "/Confere-Gallery/CG-26.jpeg" },
    { id: 53, img: "/Confere-Gallery/CG-25.jpeg" },
    { id: 54, img: "/Confere-Gallery/CG-23.jpeg" },
    { id: 55, img: "/Confere-Gallery/CG-21.jpeg" },
    { id: 56, img: "/Confere-Gallery/CG-5.jpeg" },
]

const imageFilenames = [
    "RG-1.jpeg", "RG-2.jpeg", "RG-3.jpeg", "RG-4.jpg", "RG-5.jpg",
    "RG-6.jpg", "RG-7.jpg", "RG-8.jpg", "RG-9.jpg", "RG-10.jpeg",
    "RG-11.jpeg", "RG-12.jpeg", "RG-13.jpeg", "RG-14.jpeg", "RG-15.jpeg",
    "RG-16.jpeg", "RG-17.jpeg", "RG-18.jpeg", "RG-19.jpeg", "RG-20.jpeg",
    "RG-21.jpeg", "RG-22.jpeg", "RG-23.jpeg", "RG-24.jpeg", "RG-25.jpeg",
    "RG-26.jpeg", "RG-27.jpeg", "RG-28.jpeg", "RG-29.jpeg", "RG-30.jpeg",
    "RG-22.jpeg", "RG-12.jpeg", "RG-13.jpeg", "RG-14.jpeg", "RG-15.jpeg",
    "RG-26.jpeg", "RG-27.jpeg", "RG-18.jpeg", "RG-19.jpeg", "RG-20.jpeg",
    "RG-21.jpeg", "RG-22.jpeg", "RG-23.jpeg", "RG-24.jpeg", "RG-25.jpeg",
    "RG-16.jpeg", "RG-17.jpeg", "RG-18.jpeg", "RG-19.jpeg", "RG-1.jpeg",
    "RG-11.jpeg", "RG-2.jpeg", "RG-3.jpeg", "RG-4.jpg", "RG-5.jpg",
    "RG-14.jpeg"
];
export const receptionGallery = imageFilenames.map((filename, index) => ({
    id: index + 1,
    img: `/Recep-Gallery/${filename}`
}));


const imgFilenames = [
    "SG-1.jpeg", "SG-2.jpeg", "SG-3.jpeg", "SG-4.jpeg", "SG-5.jpeg",
    "SG-6.jpeg", "SG-7.jpeg", "SG-8.jpeg", "SG-9.jpeg", "SG-10.jpeg",
    "SG-11.jpeg", "SG-12.jpeg", "SG-13.jpeg", "SG-14.jpeg", "SG-15.jpeg",
    "SG-16.jpeg", "SG-17.jpeg", "SG-18.jpeg", "SG-19.jpeg", "SG-20.jpeg",
    "SG-21.jpeg", "SG-22.jpeg", "SG-23.jpeg", "SG-24.jpeg", "SG-25.jpeg",
    "SG-26.jpeg", "SG-27.jpeg", "SG-28.jpeg", "SG-29.jpeg", "SG-30.jpeg",
    "SG-22.jpeg", "SG-12.jpeg", "SG-13.jpeg", "SG-14.jpeg", "SG-15.jpeg",
    "SG-26.jpeg", "SG-27.jpeg", "SG-18.jpeg", "SG-19.jpeg", "SG-20.jpeg",
    "SG-21.jpeg", "SG-22.jpeg", "SG-23.jpeg", "SG-24.jpeg", "SG-25.jpeg",
    "SG-16.jpeg", "SG-17.jpeg", "SG-18.jpeg", "SG-19.jpeg", "SG-1.jpeg",
    "SG-11.jpeg", "SG-2.jpeg", "SG-3.jpeg", "SG-4.jpeg", "SG-5.jpeg",
    "SG-14.jpeg"
];
export const storageGallery = imgFilenames.map((filename, index) => ({
    id: index + 1,
    img: `/Stora-Gallery/${filename}`
}));

