const specifications = [
    { label: "Customized Executive Desk", value: "L Shape/Straight" },
    { label: "Material", value: "Egger German Board" },
    { label: "Dimensions", value: "Can be Customized (Please contact our sale team)" },
    { label: "Finishes", value: "100+ Color Options" },
    { label: "Wire Managers", value: "Grommets for Every Desk" },
    { label: "Free Design Consultation", value: "by our expert design team" },
    { label: "Warranty", value: "5 Years" },
    { label: "Free Delivery and Installation", value: "within Dubai/Abu Dhabi/Sharjah/Ajman" },
    { label: "Delivery Lead-Time", value: "7-10 working days upon payment" },
];


export const chairAllImagesExecutive = [
    {
        id: 1,
        img: "/NavbarContentImg/Chair/Exec/1.jpeg",
        title: "ACE EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 2,
        img: "/NavbarContentImg/Chair/Exec/2.jpeg",
        title: "ACE MEDIUM CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 3,
        img: "/NavbarContentImg/Chair/Exec/3.jpg",
        title: "AXIOM EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 4,
        img: "/NavbarContentImg/Chair/Exec/4.jpeg",
        title: "BENZO EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 5,
        img: "/NavbarContentImg/Chair/Exec/5.jpeg",
        title: "BERLIN EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 6,
        img: "/NavbarContentImg/Chair/Exec/6.jpeg",
        title: "CASSY EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 7,
        img: "/NavbarContentImg/Chair/Exec/7.jpeg",
        title: "DAZE EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 8,
        img: "/NavbarContentImg/Chair/Exec/8.jpeg",
        title: "DOVE EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 9,
        img: "/NavbarContentImg/Chair/Exec/9.jpg",
        title: "AQUA EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 10,
        img: "/NavbarContentImg/Chair/Exec/10.jpeg",
        title: "MEDIUM PACE EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 11,
        img: "/NavbarContentImg/Chair/Exec/11.jpg",
        title: "CASE FULL EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 12,
        img: "/NavbarContentImg/Chair/Exec/12.jpg",
        title: "OSLO EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 13,
        img: "/NavbarContentImg/Chair/Exec/13.jpg",
        title: "KICKS EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 14,
        img: "/NavbarContentImg/Chair/Exec/14.jpg",
        title: "MAJESTY EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 15,
        img: "/NavbarContentImg/Chair/Exec/15.jpg",
        title: "MAJESTY MEDIUM EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 16,
        img: "/NavbarContentImg/Chair/Exec/16.jpg",
        title: "MAJOR EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 17,
        img: "/NavbarContentImg/Chair/Exec/17.jpeg",
        title: "NYLE EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 18,
        img: "/NavbarContentImg/Chair/Exec/18.jpeg",
        title: "WOODY EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 19,
        img: "/NavbarContentImg/Chair/Exec/19.jpeg",
        title: "CLASSIC EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 20,
        img: "/NavbarContentImg/Chair/Exec/20.jpg",
        title: "CLASSIC MEDIUM EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },
    {
        id: 21,
        img: "/NavbarContentImg/Chair/Exec/21.jpg",
        title: "WOODY MEDIUM EXECUTIVE CHAIR",
        sub_title: "Executive Chair",
        specifications,
    },

]

export const chairAllImagesManager = [
    {
        id: 1,
        img: "/NavbarContentImg/Chair/Manag/1.png",
        title: "AMY MANAGER CHAIR",
        sub_title: "Manager Chair",
        specifications,
    },
    {
        id: 2,
        img: "/NavbarContentImg/Chair/Manag/2.png",
        title: "ARIAL MANAGER CHAIR",
        sub_title: "Manager Chair",
        specifications,
    },
    {
        id: 3,
        img: "/NavbarContentImg/Chair/Manag/3.jpeg",
        title: "ARIC MANAGER CHAIR",
        sub_title: "Manager Chair",
        specifications,
    },
    {
        id: 4,
        img: "/NavbarContentImg/Chair/Manag/4.png",
        title: "CARA MANAGER CHAIR",
        sub_title: "Manager Chair",
        specifications,
    },
    {
        id: 5,
        img: "/NavbarContentImg/Chair/Manag/5.jpeg",
        title: "BENZ MANAGER CHAIR",
        sub_title: "Manager Chair",
        specifications,
    },
    {
        id: 6,
        img: "/NavbarContentImg/Chair/Manag/6.jpeg",
        title: "DERBY MANAGER CHAIR",
        sub_title: "Manager Chair",
        specifications,
    },
    {
        id: 7,
        img: "/NavbarContentImg/Chair/Manag/7.jpeg",
        title: "ERIS MANAGER CHAIR",
        sub_title: "Manager Chair",
        specifications,
    },
    {
        id: 8,
        img: "/NavbarContentImg/Chair/Manag/8.jpeg",
        title: "COSLO MANAGER CHAIR",
        sub_title: "Manager Chair",
        specifications,
    },
    {
        id: 9,
        img: "/NavbarContentImg/Chair/Manag/9.png",
        title: "ERGO MANAGER CHAIR",
        sub_title: "Manager Chair",
        specifications,
    },
    {
        id: 10,
        img: "/NavbarContentImg/Chair/Manag/10.jpg",
        title: "IRVY MANAGER CHAIR",
        sub_title: "Manager Chair",
        specifications,
    },
    {
        id: 11,
        img: "/NavbarContentImg/Chair/Manag/11.jpeg",
        title: "STRIKE MANAGER CHAIR",
        sub_title: "Manager Chair",
        specifications,
    }
]

export const chairAllImagesMeeting = [
    {
        id: 1,
        img: "/NavbarContentImg/Chair/Meet/1.jpeg",
        title: "ALPHA MEETING CHAIR",
        sub_title: "Meeting Chair",
        specifications,
    },
    {
        id: 2,
        img: "/NavbarContentImg/Chair/Meet/2.jpeg",
        title: "PLUS MEETING CHAIR",
        sub_title: "Meeting Chair",
        specifications,
    },
    {
        id: 3,
        img: "/NavbarContentImg/Chair/Meet/3.png",
        title: "ARIC MEETING CHAIR",
        sub_title: "Meeting Chair",
        specifications,
    },
    {
        id: 4,
        img: "/NavbarContentImg/Chair/Meet/4.png",
        title: "BELLA MEETING CHAIR",
        sub_title: "Meeting Chair",
        specifications,
    },
    {
        id: 5,
        img: "/NavbarContentImg/Chair/Meet/5.jpeg",
        title: "ARICA MEETING CHAIR",
        sub_title: "Meeting Chair",
        specifications,
    },
    {
        id: 6,
        img: "/NavbarContentImg/Chair/Meet/6.jpeg",
        title: "EVORY MEETING CHAIR",
        sub_title: "Meeting Chair",
        specifications,
    },
    {
        id: 7,
        img: "/NavbarContentImg/Chair/Meet/7.jpg",
        title: "IRVY MEETING CHAIR",
        sub_title: "Meeting Chair",
        specifications,
    },
    {
        id: 8,
        img: "/NavbarContentImg/Chair/Meet/8.jpg",
        title: "STAN MEETING CHAIR",
        sub_title: "Meeting Chair",
        specifications,
    },
    {
        id: 9,
        img: "/NavbarContentImg/Chair/Meet/9.jpg",
        title: "CARVO MEETING CHAIR",
        sub_title: "Meeting Chair",
        specifications,
    },
    {
        id: 10,
        img: "/NavbarContentImg/Chair/Meet/10.jpg",
        title: "CHARLIE MEETING CHAIR",
        sub_title: "Meeting Chair",
        specifications,
    }
]

export const chairAllImagesOperator = [
    {
        id: 1,
        img: "/NavbarContentImg/Chair/Operat/1.png",
        title: "AMY OPERATOR CHAIR",
        sub_title: "Operator Chair",
        specifications,
    },
    {
        id: 2,
        img: "/NavbarContentImg/Chair/Operat/2.png",
        title: "AMZ OPERATOR CHAIR",
        sub_title: "Operator Chair",
        specifications,
    },
    {
        id: 3,
        img: "/NavbarContentImg/Chair/Operat/3.jpeg",
        title: "BENZ OPERATOR CHAIR",
        sub_title: "Operator Chair",
        specifications,
    },
    {
        id: 4,
        img: "/NavbarContentImg/Chair/Operat/4.png",
        title: "CARA OPERATOR CHAIR",
        sub_title: "Operator Chair",
        specifications,
    },
    {
        id: 5,
        img: "/NavbarContentImg/Chair/Operat/5.png",
        title: "DELL OPERATOR CHAIR",
        sub_title: "Operator Chair",
        specifications,
    },
    {
        id: 6,
        img: "/NavbarContentImg/Chair/Operat/6.jpeg",
        title: "DERBY OPERATOR CHAIR",
        sub_title: "Operator Chair",
        specifications,
    },
    {
        id: 7,
        img: "/NavbarContentImg/Chair/Operat/7.jpeg",
        title: "IRIS OPERATOR CHAIR",
        sub_title: "Operator Chair",
        specifications,
    },
    {
        id: 8,
        img: "/NavbarContentImg/Chair/Operat/8.jpeg",
        title: "ERVY OPERATOR CHAIR",
        sub_title: "Operator Chair",
        specifications,
    },
    {
        id: 9,
        img: "/NavbarContentImg/Chair/Operat/9.png",
        title: "LEAD OPERATOR CHAIR",
        sub_title: "Operator Chair",
        specifications,
    },
    {
        id: 10,
        img: "/NavbarContentImg/Chair/Operat/10.png",
        title: "STRIKE OPERATOR CHAIR",
        sub_title: "Operator Chair",
        specifications,
    },
    {
        id: 11,
        img: "/NavbarContentImg/Chair/Operat/11.jpeg",
        title: "CASSY OPERATOR CHAIR",
        sub_title: "Operator Chair",
        specifications,
    }
]