
const specifications = [
    { label: "Customized Executive Desk", value: "L Shape/Straight" },
    { label: "Material", value: "Egger German Board" },
    { label: "Dimensions", value: "Can be Customized (Please contact our sale team)" },
    { label: "Finishes", value: "100+ Color Options" },
    { label: "Wire Managers", value: "Grommets for Every Desk" },
    { label: "Free Design Consultation", value: "by our expert design team" },
    { label: "Warranty", value: "5 Years" },
    { label: "Free Delivery and Installation", value: "within Dubai/Abu Dhabi/Sharjah/Ajman" },
    { label: "Delivery Lead-Time", value: "7-10 working days upon payment" },
];

export const flooringAllImagesCarpet = [
    {
        id: 1,
        img: "/NavbarContentImg/Flooring/Carpet/1.png",
        title: "RED- GRID MIDNIGHT CARPET",
        sub_title: "Carpet",
        specifications,
    },
    {
        id: 2,
        img: "/NavbarContentImg/Flooring/Carpet/2.png",
        title: "RED- MAGNET CARPET",
        sub_title: "Carpet",
        specifications,
    },
    {
        id: 3,
        img: "/NavbarContentImg/Flooring/Carpet/3.png",
        title: "RED- ORION CARPET",
        sub_title: "Carpet",
        specifications,
    },
    {
        id: 4,
        img: "/NavbarContentImg/Flooring/Carpet/4.png",
        title: "RED- SOLAR CARPET",
        sub_title: "Carpet",
        specifications,
    },
    {
        id: 5,
        img: "/NavbarContentImg/Flooring/Carpet/5.png",
        title: "RED- STORM CARPET",
        sub_title: "Carpet",
        specifications,
    },
    {
        id: 6,
        img: "/NavbarContentImg/Flooring/Carpet/6.png",
        title: "RED- SUNSET CARPET",
        sub_title: "Carpet",
        specifications,
    },

]

export const flooringAllImagesLaminate = [
    {
        id: 1,
        img: "/NavbarContentImg/Flooring/Laminate/1.jpg",
        title: "BLACK OAK LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 2,
        img: "/NavbarContentImg/Flooring/Laminate/2.jpg",
        title: "BROWN NAUTIC LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 3,
        img: "/NavbarContentImg/Flooring/Laminate/3.jpg",
        title: "CLASSIC OAK LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 4,
        img: "/NavbarContentImg/Flooring/Laminate/4.jpg",
        title: "CREAN OAK LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 5,
        img: "/NavbarContentImg/Flooring/Laminate/5.jpg",
        title: "DARK OAK LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 6,
        img: "/NavbarContentImg/Flooring/Laminate/6.jpg",
        title: "EARTH OAK LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 7,
        img: "/NavbarContentImg/Flooring/Laminate/7.jpg",
        title: "GREY LINEN OAK LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 8,
        img: "/NavbarContentImg/Flooring/Laminate/8.jpg",
        title: "HAM OAK LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 9,
        img: "/NavbarContentImg/Flooring/Laminate/9.jpg",
        title: "OAK 01 LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 10,
        img: "/NavbarContentImg/Flooring/Laminate/10.jpg",
        title: "ROSE OAK LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 11,
        img: "/NavbarContentImg/Flooring/Laminate/11.jpg",
        title: "SHADE OAK LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 12,
        img: "/NavbarContentImg/Flooring/Laminate/12.jpg",
        title: "STONE OAK LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 13,
        img: "/NavbarContentImg/Flooring/Laminate/13.jpg",
        title: "TEAK OAK LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 14,
        img: "/NavbarContentImg/Flooring/Laminate/14.jpg",
        title: "VENNER OAK LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 15,
        img: "/NavbarContentImg/Flooring/Laminate/15.jpg",
        title: "WALNUT 01 LAMINATE",
        sub_title: "Laminate",
        specifications,
    },
    {
        id: 16,
        img: "/NavbarContentImg/Flooring/Laminate/16.jpg",
        title: "WHITE WASHED LAMINATE",
        sub_title: "Laminate",
        specifications,
    }
]